WITH RECURSIVE TMP AS ( 
  SELECT
    F1.ID,
    F1.PARENTFOLDERID,
    F1.FOLDERNAME,
    F1.AUTHORITYID,
    F1.DISPORDER,
    ROW_NUMBER() OVER (ORDER BY DISPORDER) AS RN
  FROM
    RT2_APPLICATION_FOLDER F1
  WHERE
    F1.CORPID = '${param.corpId}'
)
,
TMPFOLDER AS (
  SELECT
    F2.ID,
    F2.PARENTFOLDERID,
    F2.FOLDERNAME,
    F2.AUTHORITYID,
    F2.DISPORDER,
    1 AS LEVEL,
    ARRAY [RN] AS SORTARRAY
  FROM
    TMP F2
  WHERE
   <#if param.folderId?has_content> 
     F2.ID IN (${param.folderId})
   <#else>
     F2.PARENTFOLDERID IS NULL
   </#if>
  UNION
  SELECT
    F2.ID,
    F2.PARENTFOLDERID,
    F2.FOLDERNAME,
    F2.AUTHORITYID,
    F2.DISPORDER,
    P.LEVEL + 1 AS LEVEL,
    ARRAY_APPEND(P.SORTARRAY, F2.RN) AS SORTARRAY 
  FROM
    TMP F2,
    TMPFOLDER P
  WHERE
    P.ID = F2.PARENTFOLDERID
) 
,
TMPFOLDER2 AS (

SELECT DISTINCT
  F.ID,
  F.PARENTFOLDERID,
  F.FOLDERNAME,
  F.AUTHORITYID,
  LPAD('・', LEVEL - 1, '・') || F.FOLDERNAME AS FOLDERNAMELEVEL,
  LEVEL,
  F.DISPORDER,
  SORTARRAY 
FROM
  TMPFOLDER F
  INNER JOIN ZT2_AUTHORITY A
    ON A.ID = AUTHORITYID
)
SELECT
  AM.*
FROM
  RT2_APPLICATION_MATTER AM
INNER JOIN FT2_BASE_FORM BF ON
  AM.APPFORM = BF.BASEFORM
INNER JOIN TMPFOLDER2 F2
  ON AM.APPFOLDERID = F2.ID
WHERE
  1 = 1
  <#if param.sDate?has_content && param.eDate?has_content> 
    AND AM.LASTUPDATE >= '${param.dStartDate?date}'
    AND AM.LASTUPDATE <= '${param.dEndDate?date}'
  </#if>
  <#if param.option == "true">
    AND (AM.USESTARTDATE IS NULL OR AM.USESTARTDATE <= NOW()::DATE)
    AND (AM.USEENDDATE IS NULL OR AM.USEENDDATE >= NOW()::DATE)
  </#if>
ORDER BY
	F2.SORTARRAY,
	AM.LISTORDER
	