WITH 
<#if param.folderId ? has_content>
SELECTED_FOLDERS AS (
		WITH RECURSIVE TMP AS (
	       SELECT 
			 FOLDER.ID 
	       FROM 
			 QT2_FILE_FOLDER FOLDER 
	       WHERE 
			 FOLDER.ID = ${param.folderId}
	       UNION 
	       SELECT 
			 FOLDER.ID 
	       FROM 
			 QT2_FILE_FOLDER FOLDER, TMP UPPERFOLDER 
	       WHERE 
			 FOLDER.UPPERFOLDERID = UPPERFOLDER.ID 
		)
		SELECT FD.* FROM TMP FD 
),
</#if>		
TEMP1 AS (
	WITH SUM_FILE AS ( 
			SELECT 
				QFF.ID, QFF.TITLE, FILESIZE, QFI.ID AS FILEID
			FROM 
		       	QT2_FILE_FOLDER QFF 
		       	INNER JOIN QT2_FILE_INFO QFI ON QFF.ID = QFI.FOLDERID 
		       	INNER JOIN QT2_FILE_ATTACH_GEN QFA ON QFI.ID = QFA.FILEID 
				INNER JOIN QT2_FILE_DATA QFD ON QFA.DOCID = QFD.DOCID 
				<#if param.folderId ? has_content>	
				INNER JOIN SELECTED_FOLDERS FO ON FO.ID = QFF.ID
				</#if>
			WHERE 
		       QFI.LASTUPDATE <= to_timestamp('${param.date} 23:59:59.999', 'YYYYMMDD HH24:MI:SSXXX') 
		       AND QFI.DRAFTFLAG = '0' 
		       AND QFI.FOLDERID IS NOT NULL		        
			
		         
			UNION ALL
		
			SELECT 
		       QFF.ID, QFF.TITLE, FILESIZE, QFI.ID AS FILEID
		    FROM 
		       QT2_FILE_FOLDER QFF 
		       INNER JOIN QT2_FILE_INFO QFI ON QFF.ID = QFI.FOLDERID 
		       INNER JOIN QT2_FILE_ATTACH_GEN QFA ON QFI.ID = QFA.FILEID 
		       INNER JOIN QT2_PDF_DATA QPD ON QFA.DOCID = QPD.PDFDATAID 
		       <#if param.folderId ? has_content>	
		       INNER JOIN SELECTED_FOLDERS FO ON FO.ID = QFF.ID
		       </#if>
		    WHERE 
		       QFI.LASTUPDATE <= to_timestamp('${param.date} 23:59:59.999', 'YYYYMMDD HH24:MI:SSXXX') 
		       AND QFI.DRAFTFLAG = '0' 
		       AND QFI.FOLDERID IS NOT NULL 
		       AND QFA.PDFCONVSTATUS = 2
		       
		)
	SELECT ID, TITLE, SUM(FILESIZE) AS FILESIZE, COUNT(DISTINCT FILEID) AS COUNTGROUPBY
	FROM SUM_FILE
	
	GROUP BY ID, TITLE
)
, TEMP2 AS (
   WITH RECURSIVE FILE_FOLDER AS (
     SELECT 
       FOLDER.ID, ARRAY[ROW_NUMBER() OVER (ORDER BY TITLE) ] AS SORT_KEY, 
       ARRAY[CAST(TITLE AS TEXT) ] AS PATH_KEY, '' AS PATH 
     FROM 
       QT2_FILE_FOLDER FOLDER 
     WHERE 
       FOLDER.UPPERFOLDERID IS NULL 
       
     UNION 
     
     SELECT 
       F.ID, ARRAY_APPEND(P.SORT_KEY, ROW_NUMBER() OVER (ORDER BY F.TITLE)) AS SORT_KEY, 
       ARRAY_APPEND(P.PATH_KEY, CAST (F.TITLE AS TEXT)) AS PATH_KEY, 
       ARRAY_TO_STRING(P.PATH_KEY, '/') AS PATH 
     FROM 
       QT2_FILE_FOLDER F, FILE_FOLDER P 
     WHERE 
       F.UPPERFOLDERID = P.ID ) 
   SELECT 
     F.ID AS FOLDERID, F.PATH, F.SORT_KEY 
   FROM 
     FILE_FOLDER F 
)
SELECT 
   TEMP1.TITLE, CEIL(TEMP1.FILESIZE * ${param.attachFactor}) AS FILESIZE, TEMP1.COUNTGROUPBY, TEMP2.PATH, TEMP2.SORT_KEY
 FROM 
   TEMP1, TEMP2
 WHERE 
   TEMP1.ID = TEMP2.FOLDERID