WITH SELECT_TODO AS (
	SELECT KTI.ID, KTI.ENDFLAG, KTI.REGEMPID  
	FROM KT2_TODO_INFO KTI  
	WHERE KTI.REGDATETIME <= to_timestamp('${param.date} 23:59:59.999', 'YYYYMMDD HH24:MI:SSXXX')
	<#if param.empIds?has_content>
	AND  KTI.REGEMPID IN ( ${param.empIds} )  
	</#if>
	),  

SELECT_DOCID AS (
	SELECT KTC.TODOID, KTCDC.DOCID  
	FROM KT2_TODO_COMMENT KTC  
		INNER JOIN KT2_TODO_COMMENT_DOC_CONN KTCDC ON KTC.ID = KTCDC.COMMENTID  
	
	UNION ALL  
	
	SELECT KTDC.TODOID, KTDC.DOCID 
	FROM KT2_TODO_DOC_CONN KTDC  )

SELECT HE.USERID, HE.EMPNAME, HE.EMPNAMEFURIGANA, HE.RETIREDATE, COALESCE(SCT.ENDFLAG, '0') AS ENDFLAG, 
	COALESCE(CEIL(SUM(QBD.FILESIZE) * ${param.attachFactor} ), 0) as FILESIZE,  COUNT(DISTINCT SCT.ID) AS COUNTGROUPBY  

FROM SELECT_TODO SCT  
	LEFT JOIN SELECT_DOCID SD ON  SCT.ID = SD.TODOID  
	LEFT JOIN QT2_BINARY_DATA QBD ON SD.DOCID = QBD.DOCID 
	INNER JOIN HT2_EMPLOYEE HE ON HE.EMPID = SCT.REGEMPID   

<#if param.empIds?has_content>
WHERE  HE.EMPID IN ( ${param.empIds} )  
</#if>

GROUP BY HE.USERID, HE.EMPNAME, HE.EMPNAMEFURIGANA, HE.RETIREDATE, SCT.ENDFLAG 
