SELECT 
	EMP.USERID,
	EMP.EMPNAME,
	EMP.EMPNAMEFURIGANA,
    EMP.RETIREDATE, 
	COUNT(DISTINCT INFO.ID) AS COUNTGROUPBY, 
	CEIL(COALESCE(SUM(INFO.FILESIZE), 0) * ${param.attachFactor}) AS FILESIZE
	
FROM (
	WITH SEARCH_SCHEDULE AS (
		SELECT SI.ID, SI.REPEATSCHID, SP.EMPID

		FROM KT2_SCHEDULE_INFO SI
		INNER JOIN KT2_SCHEDULE_PARTICIPANT SP ON SI.ID = SP.SCHID

		WHERE SI.ENDDATETIME <= TO_TIMESTAMP('${param.date} 23:59:59.999', 'YYYYMMDD HH24:MI:SSXXX')
		<#if param.empIds?has_content>
		AND SP.EMPID IN (${param.empIds}) 
		</#if>
	),

	SELECT_DOCID AS (
		SELECT SC.SCHID, SCDC.DOCID, SCDC.COMMENTID
		FROM KT2_SCHEDULE_COMMENT SC
		   INNER JOIN KT2_SCHEDULE_COMM_DOC_CONN SCDC ON SCDC.COMMENTID = SC.ID
		
		UNION ALL
		SELECT SDC.SCHID, SDC.DOCID, NULL AS COMMENTID
		FROM KT2_SCHEDULE_DOC_CONN SDC
		)

	-- Schedule thong thuong
	SELECT 
		SI.ID, SUM(BD.FILESIZE) AS FILESIZE, SI.EMPID
	FROM SEARCH_SCHEDULE SI
		LEFT JOIN SELECT_DOCID SD ON SI.ID = SD.SCHID
		LEFT JOIN QT2_BINARY_DATA BD ON BD.DOCID = SD.DOCID
	WHERE SI.REPEATSCHID IS NULL 
	GROUP BY SI.ID, SI.EMPID

	UNION ALL

	-- Schedule repeat
	SELECT 
		SI.REPEATSCHID AS ID, BD.FILESIZE AS FILESIZE, SI.EMPID
	FROM SEARCH_SCHEDULE SI
		INNER JOIN KT2_SCHEDULE_REPEAT_INFO SRI ON SRI.ID = SI.REPEATSCHID
		LEFT JOIN SELECT_DOCID SD ON SI.ID = SD.SCHID
		LEFT JOIN QT2_BINARY_DATA BD ON BD.DOCID = SD.DOCID
	WHERE SRI.REPEATENDDAY <= TO_DATE('${param.date}', 'YYYYMMDD') 
	GROUP BY SI.REPEATSCHID, SI.EMPID, BD.DOCID

) AS INFO	

INNER JOIN HT2_EMPLOYEE EMP ON EMP.EMPID = INFO.EMPID
GROUP BY INFO.EMPID, EMP.EMPNAME,
          EMP.EMPNAMEFURIGANA,
          EMP.RETIREDATE,
          EMP.USERID